<template>
  <v-container>
    <h1 class="tracking-in-expand text-center display-3 font-weight-bold mb-5">
      [ Experience ]
    </h1>
    <v-row class="mb-15">
      <v-card
        class="mx-auto mt-10 blur-in"
        color="#D4C7BE"
        width="500"
        max-height="200"
        raised
        outlined
      >
        <v-card-title style="font-weigth: bold; color: black">
          Full Stack Dev at ALMA
        </v-card-title>

        <v-card-subtitle style="color: black"> 2022 - Present </v-card-subtitle>

        <v-card-text style="color: black">
          Full time job at Fundación Desarrolla Guatemala for project
          ALMA.</v-card-text
        >
      </v-card>

      <v-card
        class="mx-auto mt-10 blur-in"
        color="#D4C7BE"
        width="500"
        max-height="200"
        raised
        outlined
      >
        <v-card-title style="font-weigth: bold; color: black">
          Teacher Assistant at UVG
        </v-card-title>
        <v-card-subtitle style="color: black"> 2022 - Present </v-card-subtitle>

        <v-card-text style="color: black">
          Teacher Assistant for CC2007.</v-card-text
        >
      </v-card>
    </v-row>
  </v-container>
</template>

<script>
export default {
  data: () => ({}),
  components: {},
}
</script>

<style scoped>
/* ----------------------------------------------
  Generated by AnimatiSS
  Licensed under FreeBSD License
  URL: https://xsgames.co/animatiss
  Twitter: @xsgames_
---------------------------------------------- */

.blur-in {
  animation: blur-in 1s linear both;
}
@keyframes blur-in {
  0% {
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    filter: blur(0);
    opacity: 1;
  }
}

/* ----------------------------------------------
  Generated by AnimatiSS
  Licensed under FreeBSD License
  URL: https://xsgames.co/animatiss
  Twitter: @xsgames_
---------------------------------------------- */

.tracking-in-expand {
  animation: tracking-in-expand 2s linear both;
}
@keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.2em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}
</style>

<style>
@import url('https://fonts.googleapis.com/css2?family=Abel&family=Cantarell&family=Oswald:wght@200&display=swap');
</style>
