<template>
  <v-container class="mt-10 blur-in" style="border-radius: 15px">
    <v-row class="text-center mt-4" justify="center">
      <v-col cols="auto">
        <v-btn
          text
          class="no-uppercase font-weight-light"
          style="font-family: 'Cardo', serif; font-size: 28px"
          @click="$router.push('/about')"
          to="/about"
        >
          <span style="font-family: 'Cardo', sans-serif; text-transform: none"
            >About</span
          >
        </v-btn>
      </v-col>
      <v-col cols="auto">
        <v-btn
          text
          class="no-uppercase font-weight-light"
          style="font-family: 'Cardo', serif; font-size: 28px"
          @click="$router.push('/portfolio')"
          to="/portfolio"
        >
          <span style="font-family: 'Cardo', sans-serif; text-transform: none"
            >Portfolio</span
          >
        </v-btn>
      </v-col>
      <v-col cols="auto">
        <v-btn
          text
          href="mailto: gom20347@uvg.edu.gt"
          class="no-uppercase font-weight-light"
          style="font-family: 'Cardo', serif; font-size: 28px"
        >
          <span style="font-family: 'Cardo', sans-serif; text-transform: none"
            >Contact</span
          >
        </v-btn>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
export default {
  name: 'SkillsDev',

  data: () => {
    return {}
  },
  methods: {},
}
</script>

<style lang="scss" scoped>
.container {
  width: 50%;
  height: 15%;
  background-color: #f2ebe0;
}
</style>

<style>
@import url('https://fonts.googleapis.com/css2?family=Abel&family=Cantarell&family=Oswald:wght@200&display=swap');
</style>

<style scoped>
/* ----------------------------------------------
  Generated by AnimatiSS
  Licensed under FreeBSD License
  URL: https://xsgames.co/animatiss
  Twitter: @xsgames_
---------------------------------------------- */

.blur-in {
  animation: blur-in 0.5s linear both;
}
@keyframes blur-in {
  0% {
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    filter: blur(0);
    opacity: 1;
  }
}

/* ----------------------------------------------
  Generated by AnimatiSS
  Licensed under FreeBSD License
  URL: https://xsgames.co/animatiss
  Twitter: @xsgames_
---------------------------------------------- */

.tracking-in-expand {
  animation: tracking-in-expand 0.001s linear both;
}
@keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.2em;
    opacity: 0;
  }
  40% {
    opacity: 0.3;
  }
  100% {
    opacity: 1;
  }
}

.glitch1 {
  animation: glitch 1s linear infinite;
}

@keyframes glitch {
  2%,
  64% {
    transform: translate(3px, 0) skew(0deg);
  }
  4%,
  60% {
    transform: translate(-3px, 0) skew(0deg);
  }
  62% {
    transform: translate(0, 0) skew(5deg);
  }
}

.glitch1:before,
.glitch1:after {
  content: attr(title);
  position: absolute;
  left: 0;
}

.glitch1:before {
  animation: glitchTop 1s linear infinite;
  clip-path: polygon(0 0, 100% 0, 100% 33%, 0 33%);
  -webkit-clip-path: polygon(0 0, 100% 0, 100% 33%, 0 33%);
}

@keyframes glitchTop {
  2%,
  64% {
    transform: translate(2px, -2px);
  }
  4%,
  60% {
    transform: translate(-2px, 2px);
  }
  62% {
    transform: translate(13px, -1px) skew(-13deg);
  }
}

.glitch1:after {
  animation: glitchBotom 1.5s linear infinite;
  clip-path: polygon(0 67%, 100% 67%, 100% 100%, 0 100%);
  -webkit-clip-path: polygon(0 67%, 100% 67%, 100% 100%, 0 100%);
}

@keyframes glitchBotom {
  2%,
  64% {
    transform: translate(-2px, 0);
  }
  4%,
  60% {
    transform: translate(-2px, 0);
  }
  62% {
    transform: translate(-22px, 5px) skew(21deg);
  }
}
</style>
