<template>
  <v-container style="border-radius: 91px" class="mt-5">
    <v-row class="text-center tracking-in-expand">
      <v-col cols="12">
        <img
          :src="compu"
          @mouseover="compu = piano"
          @mouseout="compu = require('../assets/desktop.png')"
          class="my-3 mt-15 mb-5"
          contain
          height="200"
        />
        <img
          :src="require('../assets/Ale.jpeg')"
          height="200"
          class="ml-15 my-3 mt-15 mb-5"
          style="border-radius: 30px"
        />
      </v-col>

      <v-col class="mb-10">
        <h1 class="display-2 font-weight-bold mb-1">
          Hello, I'm <u style="text-decoration: underline">Ale G</u>
        </h1>
        <h1>
          [
          <span class="typed-text">{{ typeValue }}</span>
          <span class="cursor" :class="{ typing: typeStatus }">&nbsp;</span>]
        </h1>
        <br />

        <p
          class="subheading font-weight-light mb-10"
          style="font-family: 'Cantarell', sans-serif"
        >
          Third year Computer Science Student at Universidad del Valle de
          Guatemala.
          <br />
          <br />
          Currently working at <b>ALMA Project</b>
        </p>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
export default {
  name: 'PortofolioMain',

  data: () => {
    return {
      piano: require('../assets/piano.png'),
      compu: require('../assets/desktop.png'),
      typeValue: '',
      typeStatus: true,
      typeArray: ['Full Stack Dev', 'Musician', 'Student'],
      typingSpeed: 80,
      erasingSpeed: 1,
      newTextDelay: 500,
      typeArrayIndex: 0,
      charIndex: 0,
    }
  },
  methods: {
    writeText() {
      if (this.charIndex < this.typeArray[this.typeArrayIndex].length) {
        if (!this.typeStatus) this.typeStatus = true

        this.typeValue += this.typeArray[this.typeArrayIndex].charAt(
          this.charIndex
        )
        this.charIndex += 1
        setTimeout(this.writeText, this.typingSpeed)
      } else {
        this.typeStatus = false
        setTimeout(this.deleteText, this.newTextDelay)
      }
    },
    deleteText() {
      if (this.charIndex > 0) {
        if (!this.typeStatus) this.typeStatus = true
        this.typeValue = this.typeArray[this.typeArrayIndex].substring(
          0,
          this.charIndex - 1
        )
        this.charIndex -= 1
        setTimeout(this.deleteText, this.erasingSpeed)
      } else {
        this.typeStatus = false
        this.typeArrayIndex += 1
        if (this.typeArrayIndex >= this.typeArray.length)
          this.typeArrayIndex = 0
        setTimeout(this.writeText, this.typingSpeed + 1000)
      }
    },
  },
  created() {
    setTimeout(this.writeText, this.newTextDelay + 400)
  },
}
</script>

<style lang="scss" scoped>
.container {
  width: 100%;
  height: 70%;
  background-color: #efece5;
}

h1 {
  span.typed-text {
    color: rgb(97, 95, 95);
  }
  span.cursor {
    display: inline-block;
    animation: cursorBlink 1s infinite;
  }

  span.cursor.typing {
    animation: none;
  }
}
@keyframes cursorBlink {
  49% {
    margin-left: 1%;
    background-color: gray;
  }
  50% {
    margin-left: 1%;
    background-color: transparent;
  }
  50% {
    margin-left: 1%;
    background-color: transparent;
  }
}
</style>

<style scoped>
/* ----------------------------------------------
  Generated by AnimatiSS
  Licensed under FreeBSD License
  URL: https://xsgames.co/animatiss
  Twitter: @xsgames_
---------------------------------------------- */

.blur-in {
  animation: blur-in 1s linear both;
}
@keyframes blur-in {
  0% {
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    filter: blur(0);
    opacity: 1;
  }
}

/* ----------------------------------------------
  Generated by AnimatiSS
  Licensed under FreeBSD License
  URL: https://xsgames.co/animatiss
  Twitter: @xsgames_
---------------------------------------------- */

.tracking-in-expand {
  animation: tracking-in-expand 2s linear both;
}
@keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.2em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}

.glitch1 {
  animation: glitch 1s linear infinite;
}

@keyframes glitch {
  2%,
  64% {
    transform: translate(3px, 0) skew(0deg);
  }
  4%,
  60% {
    transform: translate(-3px, 0) skew(0deg);
  }
  62% {
    transform: translate(0, 0) skew(5deg);
  }
}

.glitch1:before,
.glitch1:after {
  content: attr(title);
  position: absolute;
  left: 0;
}

.glitch1:before {
  animation: glitchTop 1s linear infinite;
  clip-path: polygon(0 0, 100% 0, 100% 33%, 0 33%);
  -webkit-clip-path: polygon(0 0, 100% 0, 100% 33%, 0 33%);
}

@keyframes glitchTop {
  2%,
  64% {
    transform: translate(2px, -2px);
  }
  4%,
  60% {
    transform: translate(-2px, 2px);
  }
  62% {
    transform: translate(13px, -1px) skew(-13deg);
  }
}

.glitch1:after {
  animation: glitchBotom 1.5s linear infinite;
  clip-path: polygon(0 67%, 100% 67%, 100% 100%, 0 100%);
  -webkit-clip-path: polygon(0 67%, 100% 67%, 100% 100%, 0 100%);
}

@keyframes glitchBotom {
  2%,
  64% {
    transform: translate(-2px, 0);
  }
  4%,
  60% {
    transform: translate(-2px, 0);
  }
  62% {
    transform: translate(-22px, 5px) skew(21deg);
  }
}
</style>
