<template>
  <v-card
    class="mx-auto mt-10 mb-15 blur-in-expand"
    max-width="1100"
    flat
    color="#96a39b"
  >
    <v-row dense>
      <v-col v-for="card in cards" :key="card.title" :cols="card.flex">
        <v-card flat :href="card.link" target="_blank">
          <v-img
            :src="card.src"
            target="_blank"
            class="white--text align-end"
            gradient="to bottom, rgba(0,0,0,.1), rgba(0,0,0,.5)"
            height="200px"
          >
            <v-card-title v-text="card.title"></v-card-title>
          </v-img>

          <v-card-actions>
            <v-spacer></v-spacer>
            <v-card-text class="align-start"
              >Link:
              <a :href="card.link" target="_blank">
                {{ card.link }}</a
              ></v-card-text
            >

            <v-btn icon :href="card.repo" target="_blank">
              <v-icon>mdi-github</v-icon>
            </v-btn>
          </v-card-actions>
        </v-card>
      </v-col>
    </v-row>
  </v-card>
</template>

<script>
export default {
  data: () => ({
    cards: [
      {
        title: 'Portfolio',
        src: require('../assets/portfolioSS.png'),
        flex: 12,
        link: 'https://portfolio-aleg001.web.app/',
        repo: 'https://github.com/aleg001/aleg-portfolio',
      },
      {
        title: 'CSS Drawing',
        src: require('../assets/cssSS.png'),
        flex: 6,
        link: 'http://juanelcaballo.club/20347/labcss/',
        repo: 'http://juanelcaballo.club/20347/labcss/',
      },
      {
        title: 'Calculator',
        src: require('../assets/calculatorSS.png'),
        flex: 6,
        link: 'https://juanelcaballo.club/20347/lab9/dist/index.html',
        repo: 'https://github.com/aleg001/Lab9---Calculadora',
      },
      {
        title: 'Vacunas GT',
        src: require('../assets/vacunasSS.png'),
        flex: 6,
        link: 'https://vacunasgt.com/',
        repo: 'https://github.com/ALMA-FUNDEGUA/vacunasgt',
      },
      {
        title: 'Memory Game',
        src: require('../assets/SolitarieSS.png'),
        flex: 6,
        link: 'https://juanelcaballo.club/20347/labreact/index.html',
        repo: 'https://github.com/aleg001/WindowsXP_LabReact',
      },
      {
        title: 'Modern Landing Page',
        src: require('../assets/landingSS.png'),
        flex: 6,
        link: 'https://aleg001.github.io/Landing-Page-Moderno/',
        repo: 'https://github.com/aleg001/Landing-Page-Moderno',
      },
      {
        title: 'Maze Game',
        src: require('../assets/mazeSS.png'),
        flex: 6,
        link: 'https://juanelcaballo.club/20347/labreact/index.html',
        repo: 'https://github.com/aleg001/WindowsXP_LabReact',
      },
    ],
  }),
}
</script>

<style scoped>
/* ----------------------------------------------
  Generated by AnimatiSS
  Licensed under FreeBSD License
  URL: https://xsgames.co/animatiss
  Twitter: @xsgames_
---------------------------------------------- */

.blur-in-expand {
  animation: blur-in-expand 0.4s linear both;
}
@keyframes blur-in-expand {
  0% {
    transform: scale(0);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    transform: scale(1);
    filter: blur(0);
    opacity: 1;
  }
}
</style>
